[package]
name = "lade-sdk"
version = "0.5.2-beta.1"
edition = "2021"
description = "Lade SDK"
license = "MPL-2.0"

[dependencies]
access-json = "0.1.0"
anyhow = "1.0.70"
async-process = "1.6.0"
async-trait = "0.1.68"
dirs = "5.0.0"
futures = "0.3.28"
itertools = "0.10.5"
log = "0.4.17"
once_cell = "1.17.1"
regex = "1.7.3"
rust-ini = "0.18.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_yaml = "0.9.19"
tempfile = "3.5.0"
tokio = { version = "1.27.0", features = ["fs"] }
toml = "0.7.3"
url = "2.3.1"
uuid = { version = "1.3.0", features = ["v4"] }
