[package]
name = "lade-sdk"
version = "0.2.1"
edition = "2021"
description = "Load automatically and hierarchically env variables from secret stores (Infisical/Dopper/1Password)."
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.69"
async-process = "1.6.0"
async-trait = "0.1.64"
futures = "0.3.26"
itertools = "0.10.5"
log = "0.4.17"
once_cell = "1.17.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tempfile = "3.4.0"
url = "2.3.1"
uuid = { version = "1.3.0", features = ["v4"] }
