[package]
name = "lade-sdk"
version = "0.9.2-beta.1"
edition = "2021"
description = "Lade SDK"
license = "MPL-2.0"

[dependencies]
access-json = "0.1.0"
anyhow = "1.0.75"
async-process = "1.7.0"
async-trait = "0.1.73"
directories = "5.0.1"
futures = "0.3.28"
itertools = "0.11.0"
log = "0.4.20"
once_cell = "1.18.0"
regex = "1.9.6"
rust-ini = "0.20.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["fs"] }
toml = "0.8.1"
url = "2.4.1"
